### ISSUE TITLE
Reads waiting until buffer is full

### ISSUE THREAD

**Issue by CarsonHoffman** [klauspost/readahead#18]
Hi!

I'm currently seeing that reads are blocking until a buffer is completely full. This doesn't fit well with my use case—mocking a TLS handshake over connections from `net.Pipe`—most reads will never fill an entire buffer, and the interleaving reads and writes of the handshake protocol mean that a read failing to immediately return deadlocks the connection. This behavior seems expected as a result of #16, however this is directly contradictory to the article introducing the library:

> Finally, there is the case where the input reader does not deliver as many bytes as we request. That is fairly common, and can indicate a lot of things. But to keep input->output latency at a minimum we forward this to output at once, even though you might have requested bigger buffers.

I have resorted to one-byte buffers to make this work; I obviously know this is less than ideal and that performance is suffering as a result, however it does now fulfill the package's goal. Is this behavior intended, and if so, is there any other workaround that you can see without knowing a minimum read size?

**Comment by klauspost** [comment]
@CarsonHoffman Yes, it was changed, since it was very inefficient in some cases to send individual reads. It is not really meant for blocking reads, and I doubt you'll see any benefits, and probably should omit it for your case.

Looking back having options on the interface would've been nice. I don't have any current plans to change this. I think for your case it also will not matter much, and not give you any benefits.

The documentation is the documentation, not the article. Things change.

**Comment by CarsonHoffman** [comment]
I see, thanks for the explanation. I do need some level of asynchronicity, not for performance reasons but because of the fact that `net.Pipe` requires a matching read for every write; because I'm simulating two ends of a connection, if they ever both try to write at the same time, we're stuck. I ended up just pinning the commit before #16; perhaps there's a simpler solution that would work for me, but I appreciate the work here nonetheless 🙂

**Comment by klauspost** [comment]
@CarsonHoffman I am open to a PR, if it can be done cleanly API-wise.

I am at the point where a refactor is getting close. Maybe it can be solved by adding `, opts ...Option`. But it is more than I can commit to right now.
