### ISSUE TITLE
io.ReadCloser supplied to NewReader is not closed

### ISSUE THREAD

**Issue by Komosa** [klauspost/readahead#3]
Doc for `func (a *reader) Close()` says that `a.in` should be closed, but there is no call to Close() on it anywhere.

**Comment by klauspost** [comment]
Thanks for notifying, that was a documentation leftover from [my original code](https://github.com/ncw/rclone/commit/6344c3051caf06c3ecd2da5148bd01391ef22b99) where an io.ReadCloser is supplied. 

I have fixed the documentation in 50e6ccf0320099fbfe7afdd021cfa208389179a9. Thanks for the report.
