### ISSUE TITLE
Allow deferring a recover

### ISSUE THREAD

**Issue by binary132** [klauspost/readahead#5]
Hello,

In case the underlying `io.Reader` panics, the host program will enter an unrecoverable state.

Would you consider adding an option to allow recovery of a panic?

**Comment by klauspost** [comment]
The most transparent method would probably be to recover it and throw it to the reader, or convert it to an error.

**Comment by binary132** [comment]
In my case I can implement a recover in my Reader implementation, but what if the panic happened in file.Read or another third-party Reader?  Using Readahead spawns a goroutine where the read happens, and that is unrecoverable.

**Comment by klauspost** [comment]
Should be fixed with #6 - Thanks for the report.

**Comment by binary132** [comment]
👍 thanks for fixing it!
