### ISSUE TITLE
Is it necessary to Close the *reader after use?

### ISSUE THREAD

**Issue by binary132** [klauspost/readahead#7]
I think that if `reader.Close` is not called, this line will block indefinitely, causing a memory "leak" of the struct and its buffers:

> https://github.com/klauspost/readahead/blob/master/reader.go#L100-L102

>```go
>100:			case <-a.exit:
>101:				return
>102:			}
>```

>```text
>once an error has been returned from the Reader, it will not recover
>```

In that case, why not just close `a.exit` when Read returns any error?

**Comment by klauspost** [comment]
It is common pattern that Close should always be called, even if an error has occurred. 

In general if you get an io. ReadCloser back, you should defer a Close.

**Comment by klauspost** [comment]
Furthermore the goroutine exits when an error occurs. Therefore buffers are free for garbage collection when the client is no longer referenced.
